<<<<<<< HEAD
smokeWebChrome=smokesuite/web/SmokeSuiteChromeWeb.xml
smokeWebEdge=smokesuite/web/SmokeSuiteEdgeWeb.xml
smokeMobile=smokesuite/mobile/SmokeSuiteChromeMobile.xml
sanityWebChrome=sanitysuite/web/SanitySuiteChromeWeb.xml
sanityWebEdge=sanitysuite/web/SanitySuiteEdgeWeb.xml
sanityMobile=sanitysuite/mobile/SanitySuiteChromeMobile.xml
regressionWebChrome=regressionsuite/web/RegressionSuiteChromeWeb.xml
regressionWebEdge=regressionsuite/web/RegressionSuiteChromeEdge.xml
regressionMobile=regressionsuite/mobile/RegressionSuiteMobile.xml

=======
smokeWebChrome=smokesuite/web/SmokeSuiteChromeWeb.xml
smokeWebEdge=smokesuite/web/SmokeSuiteEdgeWeb.xml
smokeMobile=smokesuite/mobile/SmokeSuiteChromeMobile.xml
sanityWebChrome=sanitysuite/web/SanitySuiteChromeWeb.xml
sanityWebEdge=sanitysuite/web/SanitySuiteEdgeWeb.xml
sanityMobile=sanitysuite/mobile/SanitySuiteChromeMobile.xml
regressionWebChrome=regressionsuite/web/RegressionSuiteChromeWeb.xml
regressionWebEdge=regressionsuite/web/RegressionSuiteChromeEdge.xml
regressionMobile=regressionsuite/mobile/RegressionSuiteMobile.xml

>>>>>>> f87a7e36b3caf97212464a161aa12ab913dcfde2
