MeetingPlaceAndLanguage = marShoppingMatosinhosPt
WebLocatorXML = /src/main/resources/locatorsfile/WebLocators.xml
LanguageData = /src/main/resources/jsonfiles/Language.json
TestData = /src/main/resources/jsonfiles/Testdata.json
